In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('omniart-paintings-filtered.csv')

In [3]:
df.tail()

,artwork_name,artist_full_name,creation_year,century,school,color_pallete,dominant_color,palette_count
264242,truth,circlekeeper,2008.0,21.0,modern,"[u'#a86f61', u'#a09d79', u'#372b2e', u'#252125...",#252125,"[1312, 5526, 9605, 9971, 4030, 5524, 5562, 286..."
264243,yavanna queen of the earth giver of fruits-tif...,tiffany-illustration,2017.0,21.0,modern,"[u'#ffffff', u'#feffff', u'#eef1df', u'#c0af95...",#ffffff,"[15056, 255, 5087, 6846, 9838, 1577, 4027, 476..."
264244,unknown,kano furunobu,1700.0,18.0,japanese,"[u'#b6ad97', u'#af9974', u'#a78d66', u'#a19371...",#7e4e48,"[3431, 5740, 4247, 4971, 6362, 6885, 5328, 445..."
264245,unknown,wang yuanqi,1715.0,18.0,chinese,"[u'#f8f3ed', u'#f4ede6', u'#f1e3d0', u'#edd9bb...",#e7d2b5,"[6512, 6102, 860, 6846, 4826, 5036, 5117, 3297..."
264246,portrait of a gentleman,louis-gabriel blanchet,1725.0,18.0,"France métropolitaine, France","[u'#a9977f', u'#39211a', u'#2d2b25', u'#251f1a...",#393227,"[3673, 4253, 5392, 6641, 3191, 7046, 4680, 706..."

In [4]:
mapping_df = pd.read_csv('nationality-country_dict.csv')

In [5]:
nat_to_country = dict(zip(mapping_df['nationality'], mapping_df['country']))

In [6]:
df['school'] = df['school'].map(nat_to_country).fillna(df['school'])

In [7]:
df.to_csv('omniart-paintings-filtered-clean.csv', index=False)

In [8]:
df.tail()

,artwork_name,artist_full_name,creation_year,century,school,color_pallete,dominant_color,palette_count
264242,truth,circlekeeper,2008.0,21.0,modern,"[u'#a86f61', u'#a09d79', u'#372b2e', u'#252125...",#252125,"[1312, 5526, 9605, 9971, 4030, 5524, 5562, 286..."
264243,yavanna queen of the earth giver of fruits-tif...,tiffany-illustration,2017.0,21.0,modern,"[u'#ffffff', u'#feffff', u'#eef1df', u'#c0af95...",#ffffff,"[15056, 255, 5087, 6846, 9838, 1577, 4027, 476..."
264244,unknown,kano furunobu,1700.0,18.0,Japan,"[u'#b6ad97', u'#af9974', u'#a78d66', u'#a19371...",#7e4e48,"[3431, 5740, 4247, 4971, 6362, 6885, 5328, 445..."
264245,unknown,wang yuanqi,1715.0,18.0,China,"[u'#f8f3ed', u'#f4ede6', u'#f1e3d0', u'#edd9bb...",#e7d2b5,"[6512, 6102, 860, 6846, 4826, 5036, 5117, 3297..."
264246,portrait of a gentleman,louis-gabriel blanchet,1725.0,18.0,France,"[u'#a9977f', u'#39211a', u'#2d2b25', u'#251f1a...",#393227,"[3673, 4253, 5392, 6641, 3191, 7046, 4680, 706..."